### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by lemon-room** [klich3/theatre-extensions-animations#1]
An error occurred
Uncaught TypeError: Cannot read properties of undefined (reading 'length')
See console for details.
![Screenshot from 2024-07-03 12-55-29](https://github.com/klich3/theatre-extensions-animations/assets/138027874/84daa699-750d-400f-a276-9835d5fca740)

Please help.

**Comment by klich3** [comment]
Hi there, can you provide GLTF sample file? For reproduce this error.
In console open the scene, folded item and check if get `animations` array

**Comment by lemon-room** [comment]
only in private mode, please write on info@lemonroom.ru

**Comment by lemon-room** [comment]
![Screenshot from 2024-07-03 14-25-17](https://github.com/klich3/theatre-extensions-animations/assets/138027874/efc9fe34-0806-44a2-8c6d-745541b1a505)

**Comment by lemon-room** [comment]
I got this error also with your example on r3f (linux fedora, yarn)
![Screenshot from 2024-07-03 14-30-30](https://github.com/klich3/theatre-extensions-animations/assets/138027874/2b64e42e-f7db-4a8a-8595-b3751f18aac3)

**Comment by lemon-room** [comment]
i'm trying to use in vanilla-js project like this: 
loaderGLB.load( './model/dzinka_animation_clips.glb', function ( gltf) {
  if (gltf) GLTFAnimEvent(gltf) ....
  
  is this right? I tried it in different ways:   (gltf.animations), (gltf.scene)

**Comment by lemon-room** [comment]
can you make example with threejs only please?

**Comment by lemon-room** [comment]
now example works ,when i change it to:  if (gltf) GLTFAnimEvent(gltf), 
 i'll try to use it in threejs

**Comment by klich3** [comment]
Hello friend you already have the example and small code modification.
